# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cases_pb2 as cases__pb2
import trades_pb2 as trades__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cases_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CaseStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamCases = channel.unary_stream(
                '/surveillance.CaseStream/StreamCases',
                request_serializer=trades__pb2.Empty.SerializeToString,
                response_deserializer=cases__pb2.SurveillanceCase.FromString,
                _registered_method=True)


class CaseStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamCases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CaseStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamCases': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCases,
                    request_deserializer=trades__pb2.Empty.FromString,
                    response_serializer=cases__pb2.SurveillanceCase.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'surveillance.CaseStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('surveillance.CaseStream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CaseStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamCases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/surveillance.CaseStream/StreamCases',
            trades__pb2.Empty.SerializeToString,
            cases__pb2.SurveillanceCase.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
