# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trades.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'trades.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctrades.proto\x12\x0csurveillance\"\xc9\x01\n\x0e\x43\x61nonicalTrade\x12\x15\n\revent_time_ns\x18\x01 \x01(\x03\x12\r\n\x05venue\x18\x02 \x01(\t\x12\x12\n\ninstrument\x18\x03 \x01(\t\x12\x0c\n\x04side\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x01\x12\x10\n\x08quantity\x18\x06 \x01(\x01\x12\x10\n\x08order_id\x18\x07 \x01(\t\x12\x14\n\x0c\x65xecution_id\x18\x08 \x01(\t\x12\x16\n\x0eparticipant_id\x18\t \x01(\t\x12\x0e\n\x06origin\x18\n \x01(\t\":\n\nTradeBatch\x12,\n\x06trades\x18\x01 \x03(\x0b\x32\x1c.surveillance.CanonicalTrade\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\x8d\x01\n\x0bTradeStream\x12<\n\rPublishTrades\x12\x18.surveillance.TradeBatch\x1a\x11.surveillance.Ack\x12@\n\tSubscribe\x12\x13.surveillance.Empty\x1a\x1c.surveillance.CanonicalTrade0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trades_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CANONICALTRADE']._serialized_start=31
  _globals['_CANONICALTRADE']._serialized_end=232
  _globals['_TRADEBATCH']._serialized_start=234
  _globals['_TRADEBATCH']._serialized_end=292
  _globals['_ACK']._serialized_start=294
  _globals['_ACK']._serialized_end=333
  _globals['_EMPTY']._serialized_start=335
  _globals['_EMPTY']._serialized_end=342
  _globals['_TRADESTREAM']._serialized_start=345
  _globals['_TRADESTREAM']._serialized_end=486
# @@protoc_insertion_point(module_scope)
