# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cases.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cases.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import trades_pb2 as trades__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63\x61ses.proto\x12\x0csurveillance\x1a\x0ctrades.proto\"N\n\tCaseEvent\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\r\n\x05\x61\x63tor\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x04 \x01(\t\"\xbc\x01\n\x10SurveillanceCase\x12\x0f\n\x07\x63\x61se_id\x18\x01 \x01(\t\x12\x16\n\x0eparticipant_id\x18\x02 \x01(\t\x12\x12\n\ninstrument\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x10\n\x08priority\x18\x05 \x01(\t\x12\x10\n\x08ml_score\x18\x06 \x01(\x01\x12\'\n\x06\x65vents\x18\x07 \x03(\x0b\x32\x17.surveillance.CaseEvent\x12\x0e\n\x06\x61lerts\x18\x08 \x03(\t2R\n\nCaseStream\x12\x44\n\x0bStreamCases\x12\x13.surveillance.Empty\x1a\x1e.surveillance.SurveillanceCase0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cases_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CASEEVENT']._serialized_start=43
  _globals['_CASEEVENT']._serialized_end=121
  _globals['_SURVEILLANCECASE']._serialized_start=124
  _globals['_SURVEILLANCECASE']._serialized_end=312
  _globals['_CASESTREAM']._serialized_start=314
  _globals['_CASESTREAM']._serialized_end=396
# @@protoc_insertion_point(module_scope)
