# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import trades_pb2 as trades__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in trades_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TradeStreamStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishTrades = channel.unary_unary(
                '/surveillance.TradeStream/PublishTrades',
                request_serializer=trades__pb2.TradeBatch.SerializeToString,
                response_deserializer=trades__pb2.Ack.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/surveillance.TradeStream/Subscribe',
                request_serializer=trades__pb2.Empty.SerializeToString,
                response_deserializer=trades__pb2.CanonicalTrade.FromString,
                _registered_method=True)


class TradeStreamServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PublishTrades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TradeStreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishTrades,
                    request_deserializer=trades__pb2.TradeBatch.FromString,
                    response_serializer=trades__pb2.Ack.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=trades__pb2.Empty.FromString,
                    response_serializer=trades__pb2.CanonicalTrade.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'surveillance.TradeStream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('surveillance.TradeStream', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TradeStream(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PublishTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/surveillance.TradeStream/PublishTrades',
            trades__pb2.TradeBatch.SerializeToString,
            trades__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/surveillance.TradeStream/Subscribe',
            trades__pb2.Empty.SerializeToString,
            trades__pb2.CanonicalTrade.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
